- name: Creating Digital Ocean instance(s)
  local_action:
    module: digital_ocean
    state: present
    command: droplet
    client_id: "{{ do_client_id }}"
    api_key: "{{ do_api_key }}"
    name: "{{ do_droplet_name }}"
    ssh_key_ids: "{{ do_ssh_key_ids }}"
    image_id: "{{ do_image_id }}"
    size_id: "{{ do_size_id }}"
    region_id: "{{ do_region_id }}"
    private_networking: yes
    backups_enabled: yes
    wait_timeout: 500
    unique_name: yes
    virtio: yes
  register: do_instance
- debug: msg="ID is {{ do_instance.droplet.id }}"
- debug: msg="IP is {{ do_instance.droplet.ip_address }}"
- name: Adding instances to provisionig group
  add_host: name={{ do_instance.droplet.ip_address }} groups=do_instances
