- name: Install PHP 5.5 (main packages)
  yum: pkg={{ item }} state=latest enablerepo=remi,remi-php55
  with_items:
    - "{{ php_main_packages }}"
- name: Install others PHP 5.5 packages 1
  yum: pkg={{ item }} state=latest enablerepo=remi,remi-php55
  with_items:
    - "{{ php_other_packages_1 }}"
- name: Install others PHP 5.5 packages 2
  yum: pkg={{ item }} state=latest enablerepo=remi,remi-php55
  with_items:
    - "{{ php_other_packages_2 }}"
- name: Update PHP settings
  ini_file: dest=/etc/php.ini section={{ item.section }} option={{ item.option }} value={{ item.value }} backup=yes
  with_items:
    - "{{ php_ini_settings }}"
- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
- name: Enable swap to avoid Composer Error
  shell: /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024 && /sbin/mkswap /var/swap.1 && /sbin/swapon /var/swap.1