- name: restart memcached
  service:  name=memcached state=restarted
- name: restart httpd
  service: name=httpd state=restarted
- name: restart mysqld
  service: name=mysqld state=restarted
- name: restart iptables
  service: name=iptables state=restarted
